# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Decrypt large secret
      run: |
        chmod +x ./.github/scripts/decrypt_secret.sh
        ./.github/scripts/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  deploy:
    name: Docker image deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Docker LogIn
        run: docker login -u ${{ secrets.DOCKER_USER }} -p {{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: docker build . -t "jatsqi/sac19api"
      - name: Push to registry
        run: docker push "jatsqi/sac19api"
